version: '3.9'

services:

  db-microservice:
    build: ./db-microservice
    command: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MoonStorm1
      - POSTGRES_DB=proxy_checker

  auth-microservice:
    build: ./auth-microservice
    command: gunicorn app:app --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db-microservice
    environment:
      - DATABASE_URL=postgres:MoonStorm1@db-microservice:5432/proxy_checker

  proxy-checker-microservice:
    build: ./proxy-checker-microservice
    command: gunicorn app:app --bind 0.0.0.0:8001
    depends_on:
      - db-microservice
    environment:
      - DATABASE_URL=postgresql://postgres:MoonStorm1@db-microservice:5432/proxy_checker

  proxy-filtering-microservice:
    build: ./proxy-filtering-microservice
    command: gunicorn app:app --bind 0.0.0.0:8002
    depends_on:
      - db-microservice
    environment:
      - DATABASE_URL=postgresql://postgres:MoonStorm1@db-microservice:5432/proxy_checker

  api-gateway:
    build: ./api-gateway
    command: gunicorn app:app --bind 0.0.0.0:8003
    ports:
      - "5000:5000"
    depends_on:
      - auth-microservice
      - proxy-checker-microservice
      - proxy-filtering-microservice
    environment:
      - AUTH_SERVICE_URL=http://auth-microservice:8000
      - PROXY_CHECKER_SERVICE_URL=http://proxy-checker-microservice:8001
      - PROXY_FILTERING_SERVICE_URL=http://proxy-filtering-microservice:8002

